name: Selenium Maven CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.1

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1.5.1 

      - name: Test
        run: ./mvnw test "-Dusername=${{secrets.USERNAME}}" "-Dpassword=${{secrets.PASSWORD}}"
